#!/bin/bash

set +e

DEST=anton@bonn:/mnt/mirror/backup/lima

{
    echo /bin
    echo /core
    echo /dev
    echo /home/anton/Music
    echo /home/anton/Videos
    echo /home/anton/.cache
    echo /home/anton/.thumbnails
    echo /home/anton/.local/share/Trash
    echo /home/anton/.m2
    echo /initrd.img
    echo /initrd.img.old
    echo /lib
    echo /lib32
    echo /lib64
    echo /lost+found
    echo /media
    echo /misc
    echo /mnt
    echo /proc
    echo /run
    echo /sbin
    echo /selinux
    echo /srv
    echo /swap
    echo /sys
    echo /tmp
    echo /usr
    echo /var/tmp
    echo /var/cache
    echo /var/lib
    echo /vmlinuz
    echo /vmlinuz.old
} | sudo rsync --archive --verbose --compress --progress --human-readable --delete --delete-excluded --exclude-from=- -xdev -e "ssh -i $HOME/.ssh/id_rsa" / /home "$DEST"
