#!/usr/bin/env bash

set -euo pipefail

TAG_FILE_NAME=CACHEDIR.TAG

if [ -f "$TAG_FILE_NAME" ]; then
  echo "File $TAG_FILE_NAME already exists, skipping any action."
else
  COMMENT="user $USER"
  cat <<EOF >"$TAG_FILE_NAME"
Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag created by $COMMENT.
# For information about cache directory tags, see: https://bford.info/cachedir/
EOF
fi
