#!/bin/bash
#
# Example content of duplicity.conf, keep file root:root and only owner 0600
# ---------------- 8< --------------------
# FTP_PASSWORD="ftp_password"
# PASSPHRASE="passphrase"
# TARGET="sftp://server/path"
# ---------------- 8< --------------------

if [ ! $(whoami) = root ] ; then
    echo "This script must be run by the user: root"
    exit 1
fi

HOME=/home/anton

source "$HOME/.duplicity.conf"
SOURCE=/

print_help() {
    cat <<EOF
Commands:
  backup        run backup
  stats         show collection status
  list          list files from backup
  restore       restore files from backup
Options:
  --time|-t time   specify the time from which to restore or list files
EOF
}

backup() {
    duplicity cleanup --force "$TARGET"
    duplicity remove-all-but-n-full 3 --force "$TARGET"
    nice ionice duplicity \
        --exclude-filelist "$HOME/.duplicity-exclude" \
        --full-if-older-than 2M \
        "$SOURCE" "$TARGET"
}

stats() {
    duplicity collection-status "$TARGET"
}

list() {
    duplicity list-current-files "$@" "$TARGET"
}

restore() {
    duplicity restore "$@" "$TARGET" "$(pwd)"
}

if [[ $# = 0 ]] ; then
    print_help
    exit 0
fi

while (( "$#" )) ; do
    case "$1" in
        backup)
            backup
            ;;
        stats)
            stats
            ;;
        list)
            shift
            list $*
            exit 0
            ;;
        restore)
            shift
            restore $*
            exit 0
            ;;
        *)
            print_help
            ;;
    esac
    shift
done

