#!/bin/bash
#
# Example content of duplicity.conf, keep file root:root and only owner 0600
# ---------------- 8< --------------------
# FTP_PASSWORD="ftp_password"
# PASSPHRASE="passphrase"
# TARGET="sftp://server/path"
# ---------------- 8< --------------------

if [ ! "$(whoami)" = root ] ; then
    echo "This script must be run by the user: root"
    exit 1
fi

HOME=/home/anton
REMOVE_ALL_BUT_N_FULL=4
FULL_IF_OLDER_THAN=3M

source "$HOME/.duplicity.conf"
SOURCE=/

print_help() {
    cat <<EOF
Commands:
  backup        run backup
  cleanup       cleanup
  stats         show collection status
  list          list files from backup
  restore       restore files from backup
Options:
  --time|-t time   specify the time from which to restore or list files
EOF
}

backup() {
    nice ionice duplicity $DUPLICITY_OPTS \
        --exclude-filelist "$HOME/.duplicity-exclude" \
        --full-if-older-than "$FULL_IF_OLDER_THAN" \
        "$SOURCE" "$TARGET"
    cleanup
}

cleanup() {
    duplicity $DUPLICITY_OPTS cleanup --force "$TARGET"
    duplicity $DUPLICITY_OPTS remove-all-but-n-full $REMOVE_ALL_BUT_N_FULL --force "$TARGET"
}

stats() {
    duplicity $DUPLICITY_OPTS collection-status "$TARGET"
}

list() {
    duplicity $DUPLICITY_OPTS list-current-files "$@" "$TARGET"
}

restore() {
    duplicity $DUPLICITY_OPTS restore "$@" "$TARGET" "$(pwd)"
}

if [[ $# = 0 ]] ; then
    print_help
    exit 0
fi

while (( "$#" )) ; do
    case "$1" in
        backup)
            backup
            ;;
        cleanup)
            cleanup
            ;;
        stats)
            stats
            ;;
        list)
            shift
            list "$@"
            exit 0
            ;;
        restore)
            shift
            restore "$@"
            exit 0
            ;;
        *)
            print_help
            ;;
    esac
    shift
done
