#!/bin/sh

if [ ! -x "$(command -v tesseract)" ] ; then
    echo "No tesseract executable"
    exit 1
fi
if [ ! -x "$(command -v scrot)" ] ; then
    echo "No scrot executable"
    exit 1
fi

TEMP_FILE=$(mktemp --suffix .png)
L=${1:-eng}
trap "rm $TEMP_FILE" EXIT

scrot --select --quality 100 --overwrite "$TEMP_FILE"
mogrify -modulate 100,0 -resize 400% "$TEMP_FILE"
tesseract -l $L "$TEMP_FILE" - 2>/dev/null | sed '//d' | xclip -sel clip
