#!/bin/bash

set -e

echo Connection to the VPN
sudo /usr/sbin/vpnc sibsac

echo Press any key to disconnect ...

read $disconnect

echo Disconnection from the VPN
sudo /usr/sbin/vpnc-disconnect

echo VPN should now be disconnected

