#!/bin/sh

SCR="/usr/local/bin/skype-call-recorder"

if [ -f "$SCR" ] ; then
    if !(pgrep skype-call-reco >/dev/null 2>&1) ; then
        "$SCR" &
    fi
fi
PULSE_LATENCY_MSEC=30 exec /usr/bin/skype $*
