#!/bin/bash

set -e

if [ $# = 0 ] ; then
    exit 0
fi

if ! (hash phantomjs >/dev/null 2>&1) ; then
    exit 1
fi

from=${1:0:3}
to=${1:3:3}

get_value() {
    script=$(tempfile)
    url="https://www.xe.com/currencyconverter/convert/?Amount=1&From=$from&To=$to"
    cat <<EOF >$script
    var page = require('webpage').create();
page.open('$url', function(status) {
    if (status !== 'success') {
        console.log('Unable to access network');
    } else {
        var ua = page.evaluate(function() {
            return document.querySelector('.converterresult-toAmount').textContent;
        });
        console.log(ua);
    }
    phantom.exit();
});
EOF
    timeout 15s phantomjs $script | head -n 1
    rm $script
}

get_value $from $to
